// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaCNTTUEF.Models;

#nullable disable

namespace QuanLyKhoaCNTTUEF.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20221222131653_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyKhoaCNTTUEF.Models.ChiTietTask", b =>
                {
                    b.Property<string>("IDTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IDNhom")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KetQua")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTask");

                    b.ToTable("ChiTietTask");
                });

            modelBuilder.Entity("QuanLyKhoaCNTTUEF.Models.DanhSachThongTin", b =>
                {
                    b.Property<string>("IDNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DiaChiHienTai")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IDGiaoVien")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IDKhoa")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IDSinhVien")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IDTask")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nganh")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IDNhom");

                    b.ToTable("DanhSachThongTin");
                });

            modelBuilder.Entity("QuanLyKhoaCNTTUEF.Models.KeHoach", b =>
                {
                    b.Property<string>("IDKeHoach")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTrinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDuyet")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NguoiTrinh")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKeHoach")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDKeHoach");

                    b.ToTable("KeHoach");
                });

            modelBuilder.Entity("QuanLyKhoaCNTTUEF.Models.Nhom", b =>
                {
                    b.Property<string>("IDNhom")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IDSuKien")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNhom")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDNhom");

                    b.ToTable("Nhom");
                });

            modelBuilder.Entity("QuanLyKhoaCNTTUEF.Models.SuKien", b =>
                {
                    b.Property<string>("IDSuKien")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IDNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNguoiXoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("XoaTam")
                        .HasColumnType("int");

                    b.HasKey("IDSuKien");

                    b.ToTable("SuKien");
                });

            modelBuilder.Entity("QuanLyKhoaCNTTUEF.Models.Task", b =>
                {
                    b.Property<string>("IDSuKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DanhGia")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IDTask")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("NgayBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTask")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDSuKien");

                    b.ToTable("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
